/*
 * ITU REST API
 *
 * This is documentation for our REST api for mandatory exercise 1 in the distributed systems course
 *
 * API version: 1.0.1½
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
)

func AddStudent(w http.ResponseWriter, r *http.Request) {

	w = writeSucess(w)

	var student = parseStudent(r.Body)
	fmt.Println("Adding student: " + student.Name)
	json, err := generateJsonReponse(w, fmt.Sprint("Added student with id ", student.Id))
	if err != nil {
		return
	}
	w.Write(json)
}

func DeleteStudent(w http.ResponseWriter, r *http.Request) {
	w = writeSucess(w)
}

func GetStudentById(w http.ResponseWriter, r *http.Request) {
	w = writeSucess(w)
}

func UpdateStudent(w http.ResponseWriter, r *http.Request) {

	w = writeSucess(w)
}

func UpdateStudentWithId(w http.ResponseWriter, r *http.Request) {

	w = writeSucess(w)
}
