/*
 * ITU REST API
 *
 * This is documentation for our REST api for mandatory exercise 1 in the distributed systems course
 *
 * API version: 1.0.1½
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v2/",
		Index,
	},

	Route{
		"AddCourse",
		strings.ToUpper("Post"),
		"/v2/course",
		AddCourse,
	},

	Route{
		"DeleteCourse",
		strings.ToUpper("Delete"),
		"/v2/course/{courseId}",
		DeleteCourse,
	},

	Route{
		"EnrollStudent",
		strings.ToUpper("Put"),
		"/v2/course/{courseId}/enroll/{studentId}",
		EnrollStudent,
	},

	Route{
		"GetCourseById",
		strings.ToUpper("Get"),
		"/v2/course/{courseId}",
		GetCourseById,
	},

	Route{
		"RateCourse",
		strings.ToUpper("Put"),
		"/v2/course/{courseId}/rating/{rating}",
		RateCourse,
	},

	Route{
		"UpdateCourse",
		strings.ToUpper("Put"),
		"/v2/course",
		UpdateCourse,
	},

	Route{
		"UpdateCourseWithId",
		strings.ToUpper("Post"),
		"/v2/course/{courseId}",
		UpdateCourseWithId,
	},

	Route{
		"AddStudent",
		strings.ToUpper("Post"),
		"/v2/student",
		AddStudent,
	},

	Route{
		"DeleteStudent",
		strings.ToUpper("Delete"),
		"/v2/student/{studentId}",
		DeleteStudent,
	},

	Route{
		"GetStudentById",
		strings.ToUpper("Get"),
		"/v2/student/{studentId}",
		GetStudentById,
	},

	Route{
		"UpdateStudent",
		strings.ToUpper("Put"),
		"/v2/student",
		UpdateStudent,
	},

	Route{
		"UpdateStudentWithId",
		strings.ToUpper("Post"),
		"/v2/student/{studentId}",
		UpdateStudentWithId,
	},

	Route{
		"AddTeacher",
		strings.ToUpper("Post"),
		"/v2/teacher",
		AddTeacher,
	},

	Route{
		"DeleteTeacher",
		strings.ToUpper("Delete"),
		"/v2/teacher/{teacherId}",
		DeleteTeacher,
	},

	Route{
		"GetTeacherById",
		strings.ToUpper("Get"),
		"/v2/teacher/{teacherId}",
		GetTeacherById,
	},

	Route{
		"ScoreTeacher",
		strings.ToUpper("Put"),
		"/v2/teacher/{teacherId}/score/{score}",
		ScoreTeacher,
	},

	Route{
		"UpdateTeacher",
		strings.ToUpper("Put"),
		"/v2/teacher",
		UpdateTeacher,
	},

	Route{
		"UpdateTeacherWithId",
		strings.ToUpper("Post"),
		"/v2/teacher/{teacherId}",
		UpdateTeacherWithId,
	},
}
